language: java

jdk:
  - oraclejdk8
  - oraclejdk7

os:
  - linux

branches:
  only:
    - master

script:
  - ./gradlew :spikex-core:clean
  - ./gradlew :spikex-core:build
  - ./gradlew :spikex-core:install
